# Generated by Django 4.1.4 on 2023-01-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
