# Generated by Django 4.1.4 on 2023-01-19 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_profile_phone_number_alter_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(blank=True, max_length=500)),
                ('lastname', models.TextField(blank=True, max_length=500)),
                ('post', models.TextField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('siteweb', models.TextField(blank=True, max_length=500)),
                ('type', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('rue', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=20)),
                ('codepostal', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.client')),
            ],
        ),
    ]
