# Generated by Django 4.1.4 on 2023-01-31 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_client_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientpiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(blank=True, max_length=500)),
                ('lastname', models.TextField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='etiquette',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='client',
            name='titre',
            field=models.CharField(choices=[('Madame', 'Madame'), ('Mademoiselle', 'Mademoiselle'), ('Monsieur', 'Monsieur')], default='Madame', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstname',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='post',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='siteweb',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('individu', 'individu'), ('societe', 'societe')], default='individu', max_length=20),
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clientpiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.clientpiste')),
            ],
        ),
    ]
