# Generated by Django 4.1.4 on 2023-01-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_clientpiste_client_etiquette_client_titre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpiste',
            name='firstname',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='clientpiste',
            name='lastname',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
