# Generated by Django 4.1.4 on 2023-01-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_alter_clientpiste_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientpiste',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
